// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CheckDependencies():Promise<void>;

export function GetAppInfo():Promise<model.AppInfo>;

export function OpenDir():Promise<string>;

export function OpenFile():Promise<string>;

export function SubmitFeedback(arg1:model.Feedback):Promise<boolean>;
