// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function OpenDir() {
  return window['go']['main']['App']['OpenDir']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function SubmitFeedback(arg1) {
  return window['go']['main']['App']['SubmitFeedback'](arg1);
}
