// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DockerComposeDown(arg1) {
  return window['go']['main']['Docker']['DockerComposeDown'](arg1);
}

export function DockerComposeUp(arg1) {
  return window['go']['main']['Docker']['DockerComposeUp'](arg1);
}

export function GetContainerStatus(arg1) {
  return window['go']['main']['Docker']['GetContainerStatus'](arg1);
}

export function ListContainers() {
  return window['go']['main']['Docker']['ListContainers']();
}

export function StartContainer(arg1, arg2) {
  return window['go']['main']['Docker']['StartContainer'](arg1, arg2);
}

export function StopContainer(arg1, arg2) {
  return window['go']['main']['Docker']['StopContainer'](arg1, arg2);
}

export function StreamComposeLogs(arg1) {
  return window['go']['main']['Docker']['StreamComposeLogs'](arg1);
}

export function StreamContainerLogs(arg1) {
  return window['go']['main']['Docker']['StreamContainerLogs'](arg1);
}
