// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {model} from '../models';
import {context} from '../models';

export function DockerComposeDown(arg1:main.Project):Promise<boolean>;

export function DockerComposeUp(arg1:main.Project):Promise<boolean>;

export function GetContainerStatus(arg1:string):Promise<string>;

export function ListContainers():Promise<Array<model.Container>>;

export function StartContainer(arg1:context.Context,arg2:string):Promise<boolean>;

export function StopContainer(arg1:context.Context,arg2:string):Promise<boolean>;

export function StreamComposeLogs(arg1:main.Project):Promise<void>;

export function StreamContainerLogs(arg1:main.Project):Promise<void>;
