// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateProjectFromExampleProject(arg1:string):Promise<void>;

export function DeleteProjectByID(arg1:string):Promise<boolean>;

export function FetchSandbox(arg1:string):Promise<boolean>;

export function FetchSdk(arg1:string):Promise<boolean>;

export function GetAllProjects():Promise<Array<model.Project>>;

export function GetDefaultDevNetGenesis():Promise<model.Genesis>;

export function GetDefaultMainNetGenesis():Promise<model.Genesis>;

export function GetDefaultTestNetGenesis():Promise<model.Genesis>;

export function GetProjectByID(arg1:string):Promise<model.Project>;

export function LoadConfig():Promise<boolean>;

export function New(arg1:string,arg2:string):Promise<string>;

export function SaveDevNetGenesisConfig(arg1:model.Project,arg2:model.Genesis):Promise<model.Genesis>;

export function SaveMainNetGenesisConfig(arg1:model.Project,arg2:model.Genesis):Promise<model.Genesis>;

export function SaveNewAllocationToConfig(arg1:model.Project,arg2:model.Genesis):Promise<model.Genesis>;

export function SaveProjectConfig(arg1:model.Project):Promise<model.Project>;

export function SaveTestNetGenesisConfig(arg1:model.Project,arg2:model.Genesis):Promise<model.Genesis>;

export function SetupProject(arg1:string,arg2:string):Promise<boolean>;
