// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProjectFromExampleProject(arg1) {
  return window['go']['main']['Project']['CreateProjectFromExampleProject'](arg1);
}

export function DeleteProjectByID(arg1) {
  return window['go']['main']['Project']['DeleteProjectByID'](arg1);
}

export function FetchSandbox(arg1) {
  return window['go']['main']['Project']['FetchSandbox'](arg1);
}

export function FetchSdk(arg1) {
  return window['go']['main']['Project']['FetchSdk'](arg1);
}

export function GetAllProjects() {
  return window['go']['main']['Project']['GetAllProjects']();
}

export function GetDefaultDevNetGenesis() {
  return window['go']['main']['Project']['GetDefaultDevNetGenesis']();
}

export function GetDefaultMainNetGenesis() {
  return window['go']['main']['Project']['GetDefaultMainNetGenesis']();
}

export function GetDefaultTestNetGenesis() {
  return window['go']['main']['Project']['GetDefaultTestNetGenesis']();
}

export function GetProjectByID(arg1) {
  return window['go']['main']['Project']['GetProjectByID'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['Project']['LoadConfig']();
}

export function New(arg1, arg2) {
  return window['go']['main']['Project']['New'](arg1, arg2);
}

export function SaveDevNetGenesisConfig(arg1, arg2) {
  return window['go']['main']['Project']['SaveDevNetGenesisConfig'](arg1, arg2);
}

export function SaveMainNetGenesisConfig(arg1, arg2) {
  return window['go']['main']['Project']['SaveMainNetGenesisConfig'](arg1, arg2);
}

export function SaveNewAllocationToConfig(arg1, arg2) {
  return window['go']['main']['Project']['SaveNewAllocationToConfig'](arg1, arg2);
}

export function SaveProjectConfig(arg1) {
  return window['go']['main']['Project']['SaveProjectConfig'](arg1);
}

export function SaveTestNetGenesisConfig(arg1, arg2) {
  return window['go']['main']['Project']['SaveTestNetGenesisConfig'](arg1, arg2);
}

export function SetupProject(arg1, arg2) {
  return window['go']['main']['Project']['SetupProject'](arg1, arg2);
}
