// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateAddr() {
  return window['go']['main']['SDK']['GenerateAddr']();
}

export function GetAllExampleProjectNames(arg1) {
  return window['go']['main']['SDK']['GetAllExampleProjectNames'](arg1);
}
