// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateAddr():Promise<string>;

export function GetAllExampleProjectNames(arg1:string):Promise<Array<string>>;
